services:
  api:
    build:
      context: .
    command: >
      sh -c "python manage.py react &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=lipschitz_db
      - DB_USER=lipschitz_user
      - DB_PASSWORD=Lagrangian2024!
    depends_on:
      - db
  db:
    image: postgres:14-alpine
volumes:
  postgres_data: